using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DataObjects;

namespace DataAccessInterfaces
{
    /// <summary>
    /// AUTHOR: Jonathan Beck
    /// <br />
    /// CREATED: 2024-04-17
    /// <br />
    /// 
    ///     Accessor Interface Class for Maintenance Reports
    /// </summary>
    /// 
    /// <remarks>
    /// UPDATER: [Updater's Name]
    /// <br />
    /// UPDATED: xx-xx-xx
    /// <br />
    ///     
    /// </remarks>
    public interface IDriverMaintenanceReportAccessor
    {
        /// <summary>
        ///     Adds a driver maintanance report
        /// </summary>
        /// <param name="_Driver_Maintenance_Report">
        ///    The report we are trying to add to the database
        /// </param>
        /// 
        /// <returns>
        ///    <see cref="int">bool</see>: 1 if the report was added, 0 otherwise.
        /// </returns>
        /// <remarks>
        ///    Parameters:
        /// <br />
        ///    <see cref="DriverMaintenanceReport">DriverMaintenanceReport</see> _Driver_Maintenance_Report: The report generated by the driver
        /// <br />
        ///    CONTRIBUTOR: Jonathan Beck
        /// <br />
        ///    CREATED: 2024-04-17
        /// </remarks>
        int insertDriverMaintenanceReport(DriverMaintenanceReport _driver_maintenance_report);



        /// <summary>
        ///     Retrieves all Driver Maintenance Report records from the database
        /// </summary>
        /// <returns>
        ///    List of <see cref="List{DriverMaintenanceReport}">DriverMaintenanceReport</see> objects
        /// </returns>
        /// <remarks>
        ///    Exceptions:
        /// <br />
        ///    <see cref="Exception">Exception</see>: Thrown when error encountered
        /// <br /><br />
        ///    CONTRIBUTOR: Jonathan Beck
        /// <br />
        ///    CREATED: 2024-04-22
        /// <br />
        /// <br />
        ///    UPDATER: [Updater's Name]
        /// <br />
        ///    UPDATED: yyyy-MM-dd
        /// <br />
        ///     Initial Creation
        /// </remarks>
        List<DriverMaintenanceReportVM> SelectActiveDriverMaintenaceReports();
        /// <summary>
        ///     Retrieves a single  Driver Maintenance Report record from the database
        /// </summary>
        /// <returns>
        ///    a single <see cref="DriverMaintenanceReport">DriverMaintenanceReport</see> object
        /// </returns>
        /// <remarks>
        ///    Exceptions:
        /// <br />
        ///    <see cref="Exception">Exception</see>: Thrown when error encountered
        /// <br /><br />
        ///    CONTRIBUTOR: Jonathan Beck
        /// <br />
        ///    CREATED: 2024-04-22
        /// <br />
        /// <br />
        ///    UPDATER: [Updater's Name]
        /// <br />
        ///    UPDATED: yyyy-MM-dd
        /// <br />
        ///     Initial Creation
        /// </remarks>

        DriverMaintenanceReportVM SelectAllDriverMaintenanceReportsById(int ReportID);
        /// <summary>
        ///     Retrieves all Driver Maintenance Report records from the database for a particular driver
        /// </summary>
        /// <returns>
        ///    List of <see cref="List{DriverMaintenanceReport}">DriverMaintenanceReport</see> objects related to a particular driver
        /// </returns>
        /// <remarks>
        ///  ///    Parameters:
        /// <br />
        ///    <see cref="int">DriverID</see> DriverID: The Driver whose reports we want to view
        /// <br />
        ///    Exceptions:
        /// <br />
        ///    <see cref="Exception">Exception</see>: Thrown when error encountered
        /// <br /><br />
        ///    CONTRIBUTOR: Jonathan Beck
        /// <br />
        ///    CREATED: 2024-04-22
        /// <br />
        /// <br />
        ///    UPDATER: [Updater's Name]
        /// <br />
        ///    UPDATED: yyyy-MM-dd
        /// <br />
        ///     Initial Creation
        /// </remarks>

        List<DriverMaintenanceReportVM> SelectAllDriverMaintenanceReportsByEmployeeID(int DriverID);


    }
}
