using DataObjects;
using LogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace NightRiderWPF
{
    /// <summary>
    /// Interaction logic for GuardianViewDependentList.xaml
    /// </summary>
    public partial class GuardianViewDependentList : Page
    {
        DependentVM _dependentVM = null;
        DependentManager _dependentManager = null;

        public GuardianViewDependentList()
        {
            InitializeComponent();
        }


        private void Page_Loaded(object sender, RoutedEventArgs e)
        {
            if (datDependentList.ItemsSource == null)
            {

                var dependentManager = new DependentManager();
                try
                {
                    
                    datDependentList.ItemsSource = dependentManager.GetDependentList();
                   
                    
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Database not found, please connect it.");

                }
            }

        }

        private void datDependentList_AutoGeneratedColumns(object sender, EventArgs e)
        {
            datDependentList.Columns.RemoveAt(0);
            datDependentList.Columns.RemoveAt(0);
            datDependentList.Columns.RemoveAt(2);
            datDependentList.Columns.RemoveAt(3);
            datDependentList.Columns.RemoveAt(4);
            datDependentList.Columns.RemoveAt(5);
            datDependentList.IsReadOnly = true;
        }
    }
}
